apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-replica-2
spec:
  replicas: 1
  selector:
    db: rethinkdb
    role: replica
    instance: two
  template:
    metadata:
      labels:
        db: rethinkdb
        role: replica
        instance: two
    spec:
      containers:
      - image: rosskukulinski/rethinkdb-kubernetes:2.3.4
        command:
          - "/usr/bin/run.sh"
          - "--server-name"
          - "replica_2"
          - "--cache-size"
          - "256"
        imagePullPolicy: Always
        name: rethinkdb
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RETHINK_CLUSTER
          value: rethinkdb-cluster
        ports:
        - containerPort: 8080
          name: admin-port
        - containerPort: 28015
          name: driver-port
        - containerPort: 29015
          name: cluster-port
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /data
          name: rethinkdb-storage
      volumes:
      - gcePersistentDisk:
          fsType: ext4
          pdName: rethinkdb-storage-2
        name: rethinkdb-storage
