apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-admin
spec:
  type: LoadBalancer
  ports:
   - port: 8080
     targetPort: admin-port
  selector:
    db: rethinkdb
    role: admin
---
apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-cluster
spec:
  ports:
    - port: 29015
      targetPort: cluster-port
  selector:
    db: rethinkdb
    role: replica
---
apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-driver
spec:
  ports:
    - port: 28015
      targetPort: driver-port
  selector:
    db: rethinkdb
    role: proxy
